[features]
seeds = false
skip-lint = false
[programs.devnet]
decentralized_exchange = "FXGz1xS6wL6uPXHwzSf6fS95gac9zzsYjsAnRYmZdRxn"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shree_kali/.config/solana/id.json"

[toolchain]
anchor_version = "0.29.0"
